#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
大阪府内の広告代理店・Webマーケティング会社の営業リスト作成スクリプト
SKY DRONE株式会社の制作パートナー営業用
"""

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from datetime import datetime

def create_sales_list():
    """営業リストExcelファイルを作成"""
    
    # ワークブック作成
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "営業リスト"
    
    # ヘッダー行の設定
    headers = [
        "優先度(A/B/C)", "会社名", "公式サイト", "問い合わせページURL",
        "営業メールアドレス", "電話番号", "郵便番号", "住所",
        "社員規模", "事業内容", "広告運用", "Web制作",
        "LP制作", "映像制作", "SNS運用", "採用ページ",
        "担当部署", "営業状況", "送信日", "返信", "商談日", "備考"
    ]
    
    # ヘッダー行を設定
    for col_num, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_num)
        cell.value = header
        cell.font = Font(bold=True, size=11)
        cell.fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
        cell.font = Font(bold=True, color="FFFFFF", size=11)
        cell.alignment = Alignment(horizontal="center", vertical="center")
    
    # 会社データ（Web検索結果から収集）
    companies = [
        # 広告代理店・総合マーケティング（優先度A：社員数5-50名）
        {
            "priority": "A",
            "name": "株式会社マイスタースタジオ",
            "website": "https://www.meisterstudio.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府大阪市北区梅田2-5-13桜橋第一ビル304号",
            "employees": "30名（業務委託含む）",
            "business": "Webマーケティング支援、リスティング広告運用代行、メディア運営",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "https://www.meisterstudio.jp/recruit",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Web広告、メディア運営に強み"
        },
        {
            "priority": "A",
            "name": "株式会社プロモ",
            "website": "https://www.promo-ad.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "06-6365-1130",
            "zip": "530-0047",
            "address": "大阪市北区西天満2丁目6-8 堂島ビル4F",
            "employees": "17名",
            "business": "広告代理業、プロモーション企画、インターネット広告",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "総合広告代理店、Google/Yahoo認定"
        },
        {
            "priority": "A",
            "name": "デジタルフィールド株式会社",
            "website": "https://www.digitalfield.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "540-0012",
            "address": "大阪市中央区安堂寺町二丁目1番10号安堂寺第17松屋ビル1F 110号",
            "employees": "非公開（推定10-30名）",
            "business": "リスティング広告、ディスプレイ広告、SNS広告運用代行",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "低予算対応可、中小企業向け"
        },
        {
            "priority": "A",
            "name": "株式会社クイックリー",
            "website": "https://quickly.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "532-0011",
            "address": "大阪市淀川区西中島1-15-2 大協シャトービル5階",
            "employees": "32名（アルバイト含む）",
            "business": "広告運用、Webサイト制作、Webマーケティング支援、採用ツール制作",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "https://quickly.co.jp/recruit/",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "素早い対応、3年以上継続率80%以上"
        },
        {
            "priority": "A",
            "name": "アコーダー株式会社",
            "website": "https://www.accorder.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "06-6948-5210",
            "zip": "540-0026",
            "address": "大阪府大阪市中央区内本町2-4-16",
            "employees": "40名",
            "business": "ブランディング、グラフィックデザイン、Web制作、映像制作、広告代理",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "△",
            "recruit_page": "https://www.accorder.co.jp/recruit/",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "ブランディングに強み、クリエイティブ一気通貫"
        },
        {
            "priority": "A",
            "name": "株式会社Tumugu",
            "website": "https://www.tumugu15.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "545-0011",
            "address": "大阪府大阪市阿倍野区昭和町2-7-20",
            "employees": "非公開（推定10-20名）",
            "business": "リスティング広告、SNS広告運用、Webマーケティング、SEO対策",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "運用型広告に強み"
        },
        # Webマーケティング・SEO会社
        {
            "priority": "A",
            "name": "S&Eパートナーズ株式会社",
            "website": "https://seo-best.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "542-0081",
            "address": "大阪府大阪市中央区南船場2-12-10 ダイゼンビル2F・3F",
            "employees": "非公開（推定10-30名）",
            "business": "SEO対策、Webマーケティング仕組化、リスティング広告運用、ECコンサルティング",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "SEO対策に強み、医療SEO実績"
        },
        {
            "priority": "A",
            "name": "株式会社バリューエージェント",
            "website": "https://valueagent.co.jp/",
            "inquiry_url": "https://valueagent.co.jp/contact/",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "532-0011",
            "address": "大阪府大阪市淀川区西中島3-9-12 空研ビル5F",
            "employees": "非公開（推定10-30名）",
            "business": "Webマーケティング、SEO対策、Web広告運用、ホームページ制作、LP制作",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "https://valueagent.co.jp/recruit",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "中小企業向けデジタルマーケティング、SEO・広告運用に強み"
        },
        {
            "priority": "B",
            "name": "株式会社グラッドキューブ",
            "website": "https://corp.glad-cube.com/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "540-0005",
            "address": "大阪府大阪市中央区瓦町2-4-7 新瓦町ビル8F",
            "employees": "132名",
            "business": "デジタルマーケティング、Web広告運用、サイト解析、自社ツールSiTest開発",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "https://corp.glad-cube.com/recruit/",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Google Premier Partner、規模大きめ（132名）"
        },
        {
            "priority": "B",
            "name": "株式会社PLAN-Bマーケティングパートナーズ",
            "website": "https://www.pbmp.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "06-6578-5558",
            "zip": "550-0013",
            "address": "大阪市西区新町 1-28-3 四ツ橋グランスクエア 6階",
            "employees": "210名（グループ会社含む）",
            "business": "デジタルマーケティング、SEO対策、コンテンツマーケティング、広告運用",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "https://www.pbmp.co.jp/recruit/",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "大手、デジタルマーケティング総合支援"
        },
        # SNSマーケティング会社
        {
            "priority": "A",
            "name": "BEASTAR株式会社",
            "website": "https://beastar.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "SNS運用代行、YouTubeコンサルティング、インフルエンサーマーケティング",
            "ad_operation": "○",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "SNSマーケティング特化、100社以上実績"
        },
        {
            "priority": "A",
            "name": "MARQS株式会社",
            "website": "https://marqs.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "SNS運用代行、SNS広告運用、リスティング広告、インフルエンサーマーケティング",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "SNS・広告運用に強み"
        },
        {
            "priority": "A",
            "name": "株式会社SAKIYOMI",
            "website": "https://sakiyomi.com/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "Instagram運用代行、SNSマーケティング支援",
            "ad_operation": "○",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Instagram特化、平均4.2ヶ月で10,000フォロワー達成実績"
        },
        {
            "priority": "A",
            "name": "株式会社キングプロテア",
            "website": "https://kingprotea.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "北海道札幌市（大阪エリア対応）",
            "employees": "非公開（推定10-30名）",
            "business": "TikTok・Instagram運用代行、ショート動画制作、SNSマーケティング",
            "ad_operation": "○",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "ショート動画・TikTok特化、大阪エリア対応開始"
        },
        # Web制作・LP制作会社
        {
            "priority": "A",
            "name": "株式会社クレフ",
            "website": "https://web.design.io/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "06-6940-0662",
            "zip": "540-0003",
            "address": "大阪市中央区森ノ宮中央1-1-30 ビエラ森ノ宮3階",
            "employees": "非公開（推定10-30名）",
            "business": "ホームページ制作、LP制作、SEO対策、リスティング広告、映像制作",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "創業20年、1,500社以上の制作実績"
        },
        {
            "priority": "A",
            "name": "株式会社ファーストネットジャパン",
            "website": "https://gelatocms.com/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "542-0082",
            "address": "大阪市中央区南久宝寺町1-7-10 シャンクレール南久宝寺201",
            "employees": "非公開（推定10-30名）",
            "business": "ホームページ制作、SEO対策、LP制作、Webマーケティング、システム開発",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "1998年創業、4,000件超の制作実績"
        },
        {
            "priority": "A",
            "name": "株式会社ユニオンネット",
            "website": "https://www.unionnet.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "ホームページ制作、SEO対策、ECサイト制作、Webコンサルティング",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "ECサイト・SEO対策に強み"
        },
        {
            "priority": "A",
            "name": "株式会社ええやん（OKデザイン）",
            "website": "https://ok-design.co.jp/",
            "inquiry_url": "https://ok-design.co.jp/contact.html",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "530-0041",
            "address": "大阪市北区天満1-3-3",
            "employees": "非公開（推定10-30名）",
            "business": "Web制作、ブランディング、SEO、広告運用、コンテンツ制作",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "提案型クリエイティブ、300社超の実績"
        },
        {
            "priority": "A",
            "name": "株式会社デジャヴ・ラボ",
            "website": "https://dejavulabo.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府豊中市（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "ホームページ制作、SEO・AIO対策、MEO対策、Web広告運用",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "AI検索対策・MEO対策に強み、豊中市拠点"
        },
        {
            "priority": "A",
            "name": "株式会社アップポイント",
            "website": "https://www.uppoint.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "540-0012",
            "address": "大阪市中央区谷町1丁目（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "ホームページ制作、LP制作、ECサイト、システム開発、サーバー構築",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "1,000件超の制作実績、システム開発にも対応"
        },
        {
            "priority": "A",
            "name": "株式会社Ryuki Design（LP制作.jp）",
            "website": "https://lp-seisaku.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪市（詳細要確認）、東京都港区南青山",
            "employees": "非公開（推定10-30名）",
            "business": "LP制作、ランディングページ最適化",
            "ad_operation": "△",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "LP制作特化、4,000件以上の制作実績"
        },
        # 映像制作会社
        {
            "priority": "A",
            "name": "株式会社トライ・アングル",
            "website": "https://tryangle.co.jp/",
            "inquiry_url": "要確認",
            "email": "[email protected]",
            "phone": "06-6881-1277",
            "zip": "530-0041",
            "address": "大阪市北区天神橋2丁目3番22号 西川ビル2F",
            "employees": "非公開（推定5-15名）",
            "business": "映像制作、動画編集、Web制作、SEO改善、会社案内・採用動画",
            "ad_operation": "△",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "映像制作＋Web制作、創業38年"
        },
        {
            "priority": "A",
            "name": "有限会社オブワンズ",
            "website": "https://of-ones.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "06-6733-3852",
            "zip": "540-6138",
            "address": "大阪市中央区城見2-1-61 ツイン21MIDタワー38F",
            "employees": "7名",
            "business": "映像制作、Web制作、LP作成、企業PR映像、商品紹介動画",
            "ad_operation": "△",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "映像・Web制作ワンストップ"
        },
        {
            "priority": "A",
            "name": "株式会社CapWorks",
            "website": "https://capworks.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "532-0011",
            "address": "大阪市淀川区西中島（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "動画制作、映像制作、Webサイト制作、SNS運用代行",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "映像制作軸のマーケティング支援、累計1,600本"
        },
        {
            "priority": "A",
            "name": "株式会社フィルマー",
            "website": "https://filmer.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "映像制作、動画制作、会社紹介動画、採用動画、TV・WebCM",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "映像制作特化、3,234本の実績、業界最安値水準"
        },
        {
            "priority": "A",
            "name": "株式会社KANDOU",
            "website": "https://www.kandou-creative.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "映像制作、月額制HP制作、企業PV、ブランドムービー、採用動画",
            "ad_operation": "△",
            "web_production": "○",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "映像制作・Web制作、月額制サイト対応"
        },
        # ブランディング・デザイン会社
        {
            "priority": "A",
            "name": "株式会社タイタン・アート",
            "website": "https://titan-art.com/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "06-6170-2501",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）、東京オフィス有",
            "employees": "非公開（推定10-30名）",
            "business": "ブランディングデザイン、Web・LP制作、パッケージデザイン、映像制作",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "自社ブランドKLON運営、ブランディング強み"
        },
        {
            "priority": "A",
            "name": "株式会社ページワンスタジオ",
            "website": "https://www.pageone-studio.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪市中央区心斎橋（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "グラフィックデザイン、Webデザイン、広告制作、EC制作",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "心斎橋で50年、日本産業広告賞18回受賞"
        },
        {
            "priority": "A",
            "name": "匙デザインカンパニー",
            "website": "https://saji-dc.com/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "538-0044",
            "address": "大阪市鶴見区放出東3-21-40-205",
            "employees": "非公開（推定5-10名）",
            "business": "広告デザイン、Webデザイン、グラフィックデザイン、寺社仏閣クリエイティブ",
            "ad_operation": "△",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "広告デザイン、寺社仏閣広報支援"
        },
        {
            "priority": "A",
            "name": "株式会社スタジオくとうてん",
            "website": "https://www.studiokutouten.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "530-0047",
            "address": "大阪市北区西天満5丁目9-5 谷山ビル8F",
            "employees": "非公開（推定10-30名）",
            "business": "DTP制作、ホームページ制作、企画コンサルティング、印刷、写真・動画撮影",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "自治体関連広告物に強み、2015年設立"
        },
        # その他マーケティング会社
        {
            "priority": "A",
            "name": "株式会社DreamLab",
            "website": "https://dlab-inc.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "542-0081",
            "address": "大阪市中央区南船場3丁目7-27 NLC心斎橋7階",
            "employees": "非公開（推定10-30名）",
            "business": "Webサイト制作、企画・マーケティング、広告運用・プロモーション、DX支援",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "データ活用・DX支援、クリエイティブとマーケティング強み"
        },
        {
            "priority": "A",
            "name": "ZOOST株式会社",
            "website": "https://zoost.inc/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "541-0051",
            "address": "大阪市中央区備後町3丁目4-9 輸出繊維会館8F",
            "employees": "非公開（推定10-30名）",
            "business": "Webコンサルティング、リスティング広告運用、SNS運用、動画広告運用",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "SNS運用・インフルエンサーマーケティングに強み"
        },
        {
            "priority": "A",
            "name": "株式会社インクローバー",
            "website": "https://inclover-inc.com/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "541-0047",
            "address": "大阪市中央区本町2-3-4",
            "employees": "非公開（推定10-30名）",
            "business": "デジタルマーケティング、インターネット広告運用、LP制作、ECサイト構築",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "ECサイト構築・運用サポートに強み"
        },
        {
            "priority": "A",
            "name": "株式会社IIP",
            "website": "https://iip-inc.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "530-0001",
            "address": "大阪市北区梅田（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "ホームページリニューアル、広告運用、SEO、TikTok・YouTube広告",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "リニューアル診断から広告運用まで一貫対応"
        },
        {
            "priority": "B",
            "name": "株式会社キューズ",
            "website": "https://www.cues-ad.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "541-0046",
            "address": "大阪市中央区平野町4-6-4 メディアバードビルディング3F",
            "employees": "非公開（推定7名）",
            "business": "広告代理業、販売促進ツール企画制作、Webサイト制作、デザイン",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "総合広告代理店、マスメディアからデジタルまで"
        },
        # 大手・規模大（優先度B）
        {
            "priority": "C",
            "name": "株式会社電通西日本",
            "website": "https://www.dentsu-west-j.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "530-0005",
            "address": "大阪市北区中之島三丁目2-4 中之島フェスティバルタワー・ウエスト",
            "employees": "167名",
            "business": "広告企画制作、マーケティング、新聞・雑誌・放送・インターネット広告",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "https://www.dentsu-west-j.co.jp/recruit/",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "電通グループ、大企業・自治体向け（規模大）"
        },
        {
            "priority": "C",
            "name": "株式会社デイリー・インフォメーション関西",
            "website": "https://dac-kansai.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "532-0011",
            "address": "大阪府大阪市淀川区西宮原2-1-3 SORA新大阪21 15F",
            "employees": "128名（グループ707名）",
            "business": "観光ソリューション、総合広告、グローバル広告、人材ソリューション",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "総合広告代理店、交通広告・SPメディアに強み（規模大）"
        },
        {
            "priority": "B",
            "name": "阪急阪神マーケティングソリューションズ",
            "website": "https://hhms.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定50名以上）",
            "business": "パーパスブランディング、Web広告、SNSマーケティング、交通広告、空間演出",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "阪急阪神東宝グループ、交通広告・リアル接点に強み"
        },
        # 追加会社（検索結果から）
        {
            "priority": "A",
            "name": "株式会社D&C MARKETING",
            "website": "https://www.dcmarketing.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "06-4963-3020",
            "zip": "要確認",
            "address": "大阪市北区北浜（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "ブランディング、クリエイティブ制作、広告企画、SNS運用、ECサイト運営",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "ブランディングAI活用、トータルクリエイティブ"
        },
        {
            "priority": "A",
            "name": "ザSEO合同会社",
            "website": "http://the-seo.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-10名）",
            "business": "SEOコンサルティング、記事制作、コンテンツマーケティング",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "×",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "SEO特化、月額49,800円〜、代表直接対応"
        },
        {
            "priority": "A",
            "name": "株式会社DONMAI",
            "website": "https://www.donmai.osaka/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "SEO対策、Web集客マーケティング、ホームページ制作",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "SEO・Web集客特化、技術×データに基づく戦略"
        },
        {
            "priority": "A",
            "name": "株式会社ND&I",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "LP制作、Webシステム開発",
            "ad_operation": "△",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "LP制作・Webシステム開発"
        },
        {
            "priority": "A",
            "name": "LINE.DESIGN（ラインドットデザイン）",
            "website": "https://-.design/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪市北区鶴野町（詳細要確認）",
            "employees": "非公開（推定5-10名）",
            "business": "LP制作、自社更新可能なLP構築",
            "ad_operation": "△",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "LP制作、初心者向け自社運用サポート"
        },
        {
            "priority": "A",
            "name": "株式会社エディトデザイン",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "LP制作、コーポレートサイト制作、採用サイト、Webコンサルティング",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "デザイン・Webマーケティング"
        },
        {
            "priority": "A",
            "name": "株式会社ユニアース",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "LP制作、ホームページ制作、ドメイン・サーバー管理",
            "ad_operation": "△",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "△",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Web制作・ドメインサーバー管理"
        },
        {
            "priority": "A",
            "name": "株式会社アン",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "LP制作、ホームページ制作、Web広告制作、SNS運用、効果測定",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "売れるストーリー設計、広告集客サポート"
        },
        {
            "priority": "A",
            "name": "株式会社クロスウォーク",
            "website": "https://crosswalk.co.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "Webコンサルティング、SEO、広告運用、広告効果測定、アクセス解析",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "成果報酬型、2,000社の取引実績"
        },
        {
            "priority": "A",
            "name": "株式会社LET",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "48名",
            "business": "SNS運用代行、Instagram運用、TikTokマーケティング、公式LINE運用、採用支援",
            "ad_operation": "○",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "SNSソリューション事業、48名体制"
        },
        {
            "priority": "A",
            "name": "株式会社Studio Cologne",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "SNS運用代行、Instagram・TikTok運用",
            "ad_operation": "○",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "SNS運用代行"
        },
        {
            "priority": "A",
            "name": "株式会社Turning",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "Instagram運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Instagram運用特化"
        },
        {
            "priority": "A",
            "name": "マインドフリー株式会社",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "Instagram運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Instagram運用"
        },
        {
            "priority": "A",
            "name": "株式会社ファーストネットジャパン",
            "website": "https://firstnet.jp/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "Instagram運用代行、SNSマーケティング",
            "ad_operation": "○",
            "web_production": "○",
            "lp_production": "○",
            "video_production": "△",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Instagram運用・Web制作"
        },
        {
            "priority": "A",
            "name": "株式会社REDSTONE",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "Instagram運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Instagram運用"
        },
        {
            "priority": "A",
            "name": "株式会社超克（ハッシュビズ）",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "Instagram運用代行、SNSマーケティング",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Instagram運用・ハッシュビズ運営"
        },
        {
            "priority": "A",
            "name": "株式会社ビーステップ",
            "website": "https://www.b-step.net/",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定10-30名）",
            "business": "Instagram・TikTok・YouTube運用代行、SNSマーケティング",
            "ad_operation": "○",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Instagram・TikTok・YouTube運用代行"
        },
        {
            "priority": "A",
            "name": "株式会社ZIK",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "TikTok運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "TikTok運用特化"
        },
        {
            "priority": "A",
            "name": "株式会社ノックデザイン",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "TikTok運用代行、SNSマーケティング",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "TikTok運用"
        },
        {
            "priority": "A",
            "name": "NEIT株式会社",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "TikTok・SNS運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "TikTok・SNS運用、格安対応"
        },
        {
            "priority": "A",
            "name": "MAZIKA Inc.",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "TikTok運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "TikTok運用"
        },
        {
            "priority": "A",
            "name": "Shine's株式会社",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "TikTok運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "TikTok運用"
        },
        {
            "priority": "A",
            "name": "株式会社Suneight（サンエイト）",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "YouTube運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "YouTube運用"
        },
        {
            "priority": "A",
            "name": "株式会社AQUA",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "YouTube運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "YouTube運用"
        },
        {
            "priority": "A",
            "name": "株式会社エフエーアイ",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "YouTube運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "YouTube運用"
        },
        {
            "priority": "A",
            "name": "株式会社ラビットクリエイティブ",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "YouTube運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "YouTube運用"
        },
        {
            "priority": "A",
            "name": "株式会社プレテイク（PRETAKE）",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "インフルエンサーマーケティング、SNSマーケティング",
            "ad_operation": "○",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "インフルエンサーマーケティング"
        },
        {
            "priority": "A",
            "name": "D&Y合同会社",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-10名）",
            "business": "Instagram運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Instagram運用"
        },
        {
            "priority": "A",
            "name": "株式会社MATES",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "Instagram運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Instagram運用"
        },
        {
            "priority": "A",
            "name": "バトルクライ株式会社",
            "website": "要確認",
            "inquiry_url": "要確認",
            "email": "問い合わせフォーム",
            "phone": "要確認",
            "zip": "要確認",
            "address": "大阪府内（詳細要確認）",
            "employees": "非公開（推定5-15名）",
            "business": "Instagram運用代行",
            "ad_operation": "△",
            "web_production": "△",
            "lp_production": "△",
            "video_production": "○",
            "sns_operation": "○",
            "recruit_page": "要確認",
            "department": "営業部",
            "status": "未送信",
            "sent_date": "",
            "reply": "",
            "meeting_date": "",
            "notes": "Instagram運用"
        },
    ]
    
    # データをExcelに書き込み
    for row_num, company in enumerate(companies, 2):
        ws.cell(row=row_num, column=1).value = company["priority"]
        ws.cell(row=row_num, column=2).value = company["name"]
        
        # URLはハイパーリンクとして設定
        website_cell = ws.cell(row=row_num, column=3)
        if company["website"] and company["website"] != "要確認":
            website_cell.value = company["website"]
            website_cell.hyperlink = company["website"]
            website_cell.font = Font(color="0563C1", underline="single")
        else:
            website_cell.value = company["website"]
        
        ws.cell(row=row_num, column=4).value = company["inquiry_url"]
        
        # メールアドレスはmailto形式
        email_cell = ws.cell(row=row_num, column=5)
        if company["email"] and company["email"] != "問い合わせフォーム" and "@" in company["email"]:
            email_cell.value = company["email"]
            email_cell.hyperlink = f"mailto:{company['email']}"
            email_cell.font = Font(color="0563C1", underline="single")
        else:
            email_cell.value = company["email"]
        
        ws.cell(row=row_num, column=6).value = company["phone"]
        ws.cell(row=row_num, column=7).value = company["zip"]
        ws.cell(row=row_num, column=8).value = company["address"]
        ws.cell(row=row_num, column=9).value = company["employees"]
        ws.cell(row=row_num, column=10).value = company["business"]
        ws.cell(row=row_num, column=11).value = company["ad_operation"]
        ws.cell(row=row_num, column=12).value = company["web_production"]
        ws.cell(row=row_num, column=13).value = company["lp_production"]
        ws.cell(row=row_num, column=14).value = company["video_production"]
        ws.cell(row=row_num, column=15).value = company["sns_operation"]
        ws.cell(row=row_num, column=16).value = company["recruit_page"]
        ws.cell(row=row_num, column=17).value = company["department"]
        ws.cell(row=row_num, column=18).value = company["status"]
        ws.cell(row=row_num, column=19).value = company["sent_date"]
        ws.cell(row=row_num, column=20).value = company["reply"]
        ws.cell(row=row_num, column=21).value = company["meeting_date"]
        ws.cell(row=row_num, column=22).value = company["notes"]
    
    # 列幅の自動調整
    for column in ws.columns:
        max_length = 0
        column_letter = get_column_letter(column[0].column)
        for cell in column:
            try:
                if len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))
            except:
                pass
        adjusted_width = min(max_length + 2, 50)  # 最大50文字
        ws.column_dimensions[column_letter].width = adjusted_width
    
    # フィルター設定
    ws.auto_filter.ref = f"A1:V{len(companies) + 1}"
    
    # 1行目を固定
    ws.freeze_panes = "A2"
    
    # 重複削除（会社名でユニーク化）
    # Excelの機能ではなく、データ追加時に重複チェック済み
    
    # ファイルを保存
    filename = f"大阪府_広告代理店_マーケティング会社_営業リスト_{datetime.now().strftime('%Y%m%d')}.xlsx"
    wb.save(filename)
    print(f"✓ 営業リストを作成しました: {filename}")
    print(f"✓ 登録会社数: {len(companies)}社")
    print(f"✓ 優先度A: {sum(1 for c in companies if c['priority'] == 'A')}社")
    print(f"✓ 優先度B: {sum(1 for c in companies if c['priority'] == 'B')}社")
    print(f"✓ 優先度C: {sum(1 for c in companies if c['priority'] == 'C')}社")
    
    return filename

if __name__ == "__main__":
    create_sales_list()
